#!/bin/bash

if [[ "$1" == "--tr" ]]; then
	kitty --working-directory ~ &

elif [[ "$1" == "--ff" ]]; then
	brave-beta &

elif [[ "$1" == "--fm" ]]; then
	thunar ~ &

elif [[ "$1" == "--ge" ]]; then
	geany &

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &

elif [[ "$1" == "--rd" ]]; then
	brave-beta --new-tab "https://reddit.com"

elif [[ "$1" == "--ml" ]]; then
	brave-beta --new-tab "https://mail.google.com"

elif [[ "$1" == "--pow" ]]; then
	xfce4-power-manager-settings &
fi
