#!/bin/bash

EWW=`which eww`
CFG="$HOME/.config/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 0.5
fi
# don't forget to change/add the the widgets you want to be displayed here
run_eww() {
	${EWW} --config "$CFG" open-many \
		   clock \
		   workspaces \
		   controls \
		   system \
		   launcher
}

run_eww
