#!/bin/bash

EWW=`which eww`
CFG="$HOME/.config/eww"

# don't forget to change/add the the widgets you want to be displayed here
run_eww() {
	${EWW} --restart --config "$CFG" open-many \
		   date \
		   clock \
		   workspaces \
		   controls \
		   launcher \
		   current_program
}

run_eww
