#!/bin/bash

EWW=`which eww`
CFG="$HOME/.config/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 0.5
fi

run_eww() {
	${EWW} --config "$CFG" open-many \
		   clock \
		   workspaces \
		   controls \
		   system \
		   launcher
}

run_eww
