#!/bin/bash

##  and CMD
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open background
	${EWW} open folderview
	${EWW} open bonsaiview
	${EWW} open fortune
	${EWW} open music
	${EWW} open search
	${EWW} open weather
	${EWW} open temperatur
	${EWW} open shutdown
	${EWW} open pcusage
	${EWW} open applauncher
	${EWW} open activetime
}

## Launch or close widgets accordingly
if [[ -z `eww windows | grep *folderview` ]]; then
	run_eww
else
	${EWW} close folderview
	${EWW} close bonsaiview
	${EWW} close fortune
	${EWW} close music
	${EWW} close search
	${EWW} close weather
	${EWW} close temperatur
	${EWW} close shutdown
	${EWW} close pcusage
	${EWW} close applauncher
	${EWW} close activetime
	${EWW} close background

fi
