#!/bin/bash

EWW=`which eww`
LOCK_FILE="/tmp/dashboard.lock"
## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi


## Launch or close widgets accordingly
## currently very ugly solution. 
## The script decides that the dashboard is not open 
## if it cannot find the dashboard widget 
## !TODO find a better solution
if [[ -f "$LOCK_FILE" ]]; then
	eww close dashboard
	rm "$LOCK_FILE"
else
	eww open dashboard
	touch "$LOCK_FILE"
fi
